GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/12

###

POST http://localhost:3000/subscribers

{
    "name": "Jerin Ignatious",
    "subscribedToChannel": "Talking Titans"
}