GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Jerin Ignatious",
    "subscribedToChannel": "Talking Titans"
}

###

DELETE http://localhost:3000/subscribers/

###

PATCH  http://localhost:3000/subscribers/60ec25bf8626001584eaeb5f
Content-Type: application/json

{
    "name": "Shreeraj Shivale"
}